apiVersion: v1
kind: ConfigMap
metadata:
  name: casc-oc
data:
  bundle.yaml: |
    apiVersion: "1"
    id: "jenkins"
    description: "OC Bundle"
    version: "01"
    plugins:
      - "plugins.yaml"
    jcasc:
      - "jenkins.yaml"
    rbac:
      - "rbac.yaml"
    items:
      - "items.yaml"  
  jenkins.yaml: |
   # TODO add jenkins file content 

  items.yaml: |
    removeStrategy:
      rbac: SYNC
      items: NONE
    items:
    - kind: "freeStyle"
      name: "casc-sync"
      displayName: "CasC Bundle Sync"
      description: "Syncronizes CasC Bundles."
      disabled: false
      quietPeriod: 10
      scm:
        gitSCM:
          gitTool: git
          userRemoteConfigs:
            - userRemoteConfig:
                url: "https://github.com/joostvdg/jenkins-examples.git"
      builders:
        - shell:
            command: "cp -R casc/* ${JENKINS_HOME}/jcasc-bundles-store"      
    - kind: folder
      name: casc
      description: ''
    - kind: folder
      name: myfolder
      description: ''
    - kind: folder
      name: myotherfolder
      description: ''
    - kind: folder
      name: Teams  
    - kind: managedController
      displayName: 'Blue'
      name: mc-blue
      description: 'Blue Controller (Managed)'
      groups:
      - members:
          users:
          - bluedev
          - blueadmin
        name: Blues
      properties:
      - configurationAsCode:
          bundle: mc21
      - healthReporting:
          enabled: true
      - licensing:
          strategy:
            perUserLicensingStrategy: {}
      configuration:
        kubernetes:
          memory: 3072
          cpus: 1.0
          disk: 50
          domain: blue
          yaml: ''
    - kind: managedController
      displayName: 'Green'
      name: mc-green
      description: 'Green Controller (Managed)'
      groups:
      - members:
          users:
          - greendev
          - greenadmin
        name: Greens
      properties:
      - configurationAsCode:
          bundle: mc1
      - healthReporting:
          enabled: true
      - licensing:
          strategy:
            perUserLicensingStrategy: {}
      configuration:
        kubernetes:
          memory: 3072
          cpus: 1.0
          disk: 50
          domain: green
          yaml: ''
  rbac.yaml: |
    removeStrategy:
      rbac: SYNC
    roles:
    - name: authenticated
    - permissions:
      - hudson.model.Hudson.Administer
      name: administer
    - name: anonymous
    - filterable: 'true'
      permissions:
      - hudson.model.Item.Cancel
      - hudson.model.Item.Build
      - hudson.model.Item.Move
      - hudson.model.Item.Create
      - hudson.model.View.Create
      - hudson.model.Run.Update
      - hudson.model.View.Delete
      - hudson.model.Run.Delete
      - hudson.model.View.Configure
      - hudson.model.Item.Promote
      - hudson.model.Item.Configure
      - hudson.model.Item.Read
      - hudson.scm.SCM.Tag
      - hudson.model.Item.Discover
      - hudson.model.Hudson.Read
      - hudson.model.Item.Workspace
      - hudson.model.View.Read
      - hudson.model.Item.Delete
      - hudson.model.Item.Request
      name: develop
    - filterable: 'true'
      permissions:
      - hudson.model.Item.Read
      - hudson.model.Item.Discover
      - hudson.model.Hudson.Read
      - hudson.model.View.Read
      name: browse
    groups:
    - members:
        external_groups:
          - Administrators
        users:
        - admin
      roles:
      - name: administer
        grantedAt: current
      name: Administrators
    - roles:
      - name: develop
        grantedAt: current
      name: Developers
      members:
        external_groups:
          - BlueAdmins
          - GreenAdmins
    - roles:
      - name: browse
        grantedAt: current
      name: Browsers
      members:
        external_groups:
          - Blue
          - Green
  plugins.yaml: |
      plugins:
        - id: ace-editor
        - id: apache-httpcomponents-client-4-api
        - id: async-http-client
        - id: authentication-tokens
        - id: aws-credentials
        - id: aws-java-sdk
        - id: aws-java-sdk-ec2
        - id: aws-java-sdk-elasticbeanstalk
        - id: aws-java-sdk-minimal
        - id: blueocean-commons
        - id: bootstrap4-api
        - id: bootstrap5-api
        - id: bouncycastle-api
        - id: caffeine-api
        - id: checks-api
        - id: cloudbees-administrative-monitors
        - id: cloudbees-analytics
        - id: cloudbees-assurance
        - id: cloudbees-blueocean-default-theme
        - id: cloudbees-casc-api
        - id: cloudbees-casc-client
        - id: cloudbees-casc-items-api
        - id: cloudbees-casc-items-commons
        - id: cloudbees-casc-items-server
        - id: cloudbees-casc-server
        - id: cloudbees-folder
        - id: cloudbees-folders-plus
        - id: cloudbees-license
        - id: cloudbees-monitoring
        - id: cloudbees-platform-common
        - id: cloudbees-platform-data
        - id: cloudbees-plugin-usage
        - id: cloudbees-support
        - id: cloudbees-uc-data-api
        - id: cloudbees-unified-ui
        - id: cloudbees-update-center-plugin
        - id: command-launcher
        - id: credentials
        - id: credentials-binding
        - id: display-url-api
        - id: docker-commons
        - id: durable-task
        - id: echarts-api
        - id: font-awesome-api
        - id: handy-uri-templates-2-api
        - id: infradna-backup
        - id: jackson2-api
        - id: javax-activation-api
        - id: javax-mail-api
        - id: jaxb
        - id: jdk-tool
        - id: jjwt-api
        - id: jquery3-api
        - id: junit
        - id: kube-agent-management
        - id: kubernetes
        - id: kubernetes-client-api
        - id: kubernetes-credentials
        - id: mailer
        - id: mapdb-api
        - id: master-provisioning-core
        - id: master-provisioning-kubernetes
        - id: metrics
        - id: nectar-license
        - id: nectar-rbac
        - id: node-iterator-api
        - id: oauth-credentials
        - id: okhttp-api
        - id: operations-center-agent
        - id: operations-center-clusterops
        - id: operations-center-context
        - id: operations-center-elasticsearch-provider
        - id: operations-center-kubernetes-cloud
        - id: operations-center-license
        - id: operations-center-monitoring
        - id: operations-center-server
        - id: operations-center-sso
        - id: operations-center-updatecenter
        - id: plain-credentials
        - id: plugin-util-api
        - id: popper-api
        - id: popper2-api
        - id: scm-api
        - id: script-security
        - id: snakeyaml-api
        - id: ssh-credentials
        - id: sshd
        - id: structs
        - id: support-core
        - id: token-macro
        - id: trilead-api
        - id: unique-id
        - id: user-activity-monitoring
        - id: variant
        - id: workflow-api
        - id: workflow-step-api
        - id: workflow-support