OperationsCenter:
  CasC:
    Enabled: true
  ExtraVolumes:
  - name: oc-casc-bundle
    configMap:
      name: oc-casc-bundle
      optional: true
  ExtraVolumeMounts:
  - name: oc-casc-bundle
    mountPath: /var/jenkins_config/oc-casc-bundle
    readOnly: true
  JavaOpts:
    -Dcore.casc.config.bundle=/var/jenkins_config/oc-casc-bundle

